import { BarChart3, Boxes, Building2, CheckCircle2, ClipboardList, FileText, HardHat, ReceiptText, ShieldCheck, Smartphone, Users, WalletCards } from "lucide-react";
import "./site.css";

const modules = [
  [Users,"Clientes e Filiais","Cadastros completos, equipamentos e histórico centralizado."],
  [ClipboardList,"Ordens de Serviço","Agenda, técnicos, fotos, assinaturas e relatórios."],
  [HardHat,"Gestão de Obras","Etapas, progresso, ocorrências e acompanhamento do cliente."],
  [FileText,"Vendas e Orçamentos","Propostas, pedidos e conversão integrada em OS."],
  [Boxes,"Produtos e Estoque","Compras, movimentações, reservas e alertas."],
  [WalletCards,"Financeiro","Contas, fluxo de caixa, comissões e indicadores."],
  [ReceiptText,"NFS-e","Emissão integrada ao atendimento e à ordem de serviço."],
  [BarChart3,"Relatórios","Visão gerencial com dados operacionais e financeiros."],
] as const;

export default function InstitutionalPage(){return <main className="site-root">
  <header className="site-nav"><a className="site-brand" href="#inicio"><span>PRO</span>AR <small>BY TAV&apos;s</small></a><nav><a href="#recursos">Recursos</a><a href="#multiempresa">Multiempresa</a><a href="#mobile">Aplicativo</a></nav><a className="nav-cta" href="https://teste.proar.online">Teste grátis</a></header>
  <section id="inicio" className="hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={15}/> GESTÃO COMPLETA PARA EMPRESAS DE SERVIÇOS</span><h1>Controle sua operação.<br/><em>Faça sua empresa crescer.</em></h1><p>O ProAR reúne gestão operacional, comercial e financeira em uma plataforma moderna, segura e preparada para acompanhar sua empresa todos os dias.</p><div className="hero-actions"><a className="primary" href="https://teste.proar.online">Começar teste grátis por 7 dias</a><a className="secondary" href="#recursos">Conhecer a plataforma</a></div><div className="trust"><span><CheckCircle2/> Banco isolado</span><span><CheckCircle2/> Acesso seguro</span><span><CheckCircle2/> Computador e celular</span></div></div><div className="dashboard-demo"><div className="demo-top"><i/><i/><i/><b>ProAR • Painel gerencial</b></div><div className="demo-body"><aside><strong>P</strong><span/><span/><span/><span/><span/></aside><div className="demo-content"><h3>Visão geral</h3><div className="metrics"><article><small>Ordens abertas</small><b>28</b></article><article><small>Faturamento</small><b>R$ 84 mil</b></article><article><small>Clientes ativos</small><b>147</b></article></div><div className="chart"><div/><div/><div/><div/><div/><div/><div/></div><div className="demo-list"><span/><span/><span/></div></div></div></div></section>
  <section id="recursos" className="features"><div className="section-head"><span>RECURSOS DO PROAR</span><h2>Tudo que sua empresa precisa, conectado</h2><p>Informações consistentes do primeiro atendimento ao resultado financeiro.</p></div><div className="feature-grid">{modules.map(([Icon,title,text])=><article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="multiempresa" className="tenant"><div><span className="eyebrow"><Building2 size={15}/> ARQUITETURA MULTIEMPRESA</span><h2>Um ambiente exclusivo para cada empresa</h2><p>Cada cliente possui endereço próprio, configurações, identidade e banco de dados isolado. Mais segurança, organização e independência.</p><code>suaempresa.proar.online</code><ul><li><ShieldCheck/> Dados separados por empresa</li><li><ShieldCheck/> Permissões por perfil</li><li><ShieldCheck/> Sincronização online e modo offline</li></ul></div><div className="tenant-cards"><article><b>Empresa A</b><small>empresa-a.proar.online</small><span>Banco exclusivo</span></article><article><b>Empresa B</b><small>empresa-b.proar.online</small><span>Banco exclusivo</span></article><article><b>Sua empresa</b><small>suaempresa.proar.online</small><span>Ambiente personalizado</span></article></div></section>
  <section id="mobile" className="mobile"><div className="phone"><div className="phone-screen"><small>ProAR Mobile</small><h3>Serviços de hoje</h3><article><b>OS #1048</b><span>Instalação • 09:00</span></article><article><b>OS #1049</b><span>Manutenção • 13:30</span></article><button>Iniciar atendimento</button></div></div><div><span className="eyebrow"><Smartphone size={15}/> TRABALHE EM QUALQUER LUGAR</span><h2>O escritório e a equipe técnica no mesmo sistema</h2><p>Acesse pelo computador, tablet ou celular. Consulte ordens, registre fotos, assinaturas e alterações mesmo durante o atendimento em campo.</p><div className="mobile-points"><span><CheckCircle2/> Layout responsivo</span><span><CheckCircle2/> Fotos e assinaturas</span><span><CheckCircle2/> Funcionamento offline</span></div></div></section>
  <section className="final-cta"><h2>Pronto para organizar e acelerar sua empresa?</h2><p>Conheça o ProAR por 7 dias com um ambiente exclusivo para o seu negócio.</p><a href="https://teste.proar.online">Criar meu ambiente grátis</a></section>
  <footer><div className="site-brand"><span>PRO</span>AR <small>BY TAV&apos;s</small></div><p>Gestão operacional, comercial e financeira.</p><nav><a href="/termos">Termos de Uso</a><a href="/privacidade">Privacidade</a></nav></footer>
</main>}
