"use client";

import { CalendarDays, CheckCircle2, Clock3, ImageIcon, RefreshCw, Wrench } from "lucide-react";
import { use, useEffect, useState } from "react";

type TimelineEvent = { id:string; createdAt:string; status:string; customerNote?:string; photos?:string[]; customerVisible?:boolean };
type PublicOrder = { orderId:string; client:string; service:string; date:string; time:string; status:string; timeline:TimelineEvent[]; updatedAt:string };
export default function PublicServiceOrder({ params }:{ params:Promise<{token:string}> }) {
  const { token } = use(params); const [order,setOrder]=useState<PublicOrder|null>(null); const [error,setError]=useState("");
  const load=async()=>{try{const response=await fetch(`/api/public-service-order?token=${encodeURIComponent(token)}`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);setOrder(result.order);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível carregar a OS.");}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer);},[token]);
  return <main style={{minHeight:"100vh",padding:"24px",background:"#031426",color:"#eaf4ff",fontFamily:"Arial, sans-serif"}}><section style={{maxWidth:860,margin:"0 auto",display:"grid",gap:16}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,padding:"20px",border:"1px solid #1c466d",borderRadius:16,background:"#071e35"}}><div><small style={{color:"#4fa8ff",fontWeight:800}}>PROAR • ACOMPANHAMENTO DE ORDEM DE SERVIÇO</small><h1 style={{margin:"8px 0 4px",fontSize:24}}>{order?.orderId || "Carregando OS"}</h1><p style={{margin:0,color:"#a9c2dc"}}>Acompanhe somente as atualizações liberadas pela equipe.</p></div><button onClick={load} style={{display:"flex",alignItems:"center",gap:7,padding:"10px 12px",border:"1px solid #2d72a8",borderRadius:8,background:"#0d3154",color:"#fff"}}><RefreshCw size={15}/> Atualizar</button></header>{error?<section style={{padding:16,border:"1px solid #9b3b45",borderRadius:12,background:"#35131b"}}>{error}</section>:!order?<section style={{padding:28,textAlign:"center",border:"1px solid #1c466d",borderRadius:12}}>Carregando atualizações...</section>:<><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}>{[[Wrench,"SERVIÇO",order.service],[CalendarDays,"AGENDAMENTO",order.date?`${new Date(`${order.date}T12:00:00`).toLocaleDateString("pt-BR")} • ${order.time||"A definir"}`:"A definir"],[CheckCircle2,"STATUS",order.status]].map(([Icon,label,value])=>{const C=Icon as typeof Wrench;return <article key={String(label)} style={{padding:15,border:"1px solid #1c466d",borderRadius:12,background:"#071e35"}}><C size={17} color="#4fa8ff"/><small style={{display:"block",marginTop:8,color:"#90aac5"}}>{String(label)}</small><b>{String(value)}</b></article>})}</section><section style={{padding:20,border:"1px solid #1c466d",borderRadius:16,background:"#071e35"}}><h2 style={{marginTop:0,fontSize:18}}>Linha do tempo</h2>{order.timeline.filter(event=>event.customerVisible).length? [...order.timeline].filter(event=>event.customerVisible).reverse().map(event=><article key={event.id} style={{display:"grid",gridTemplateColumns:"12px 1fr",gap:10,padding:"11px 0",borderTop:"1px solid #153957"}}><i style={{width:10,height:10,marginTop:4,borderRadius:"50%",background:"#1c8cff"}}/><div><b>{event.status}</b><small style={{display:"block",marginTop:3,color:"#8aa6c1"}}><Clock3 size={12} style={{verticalAlign:"-2px"}}/> {new Date(event.createdAt).toLocaleString("pt-BR")}</small>{event.customerNote&&<p style={{margin:"8px 0",color:"#d7e6f5"}}>{event.customerNote}</p>}{event.photos?.length?<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{event.photos.map((photo,index)=><img key={index} src={photo} alt={`Atualização ${index+1}`} style={{width:110,height:82,borderRadius:8,objectFit:"cover"}}/>)}</div>:null}</div></article>):<p style={{color:"#a9c2dc"}}><ImageIcon size={15}/> Nenhuma atualização liberada ainda.</p>}</section></>}</section></main>;
}
