"use client";
import { useEffect, useState } from "react";
import type { WorkRoute } from "@/lib/work-routes";
import "./work-routes.css";
type Summary = Omit<WorkRoute,"points"> & {pointCount:number;imprecisePoints:number;lastPoint?:WorkRoute["points"][number]};
const date = (value?:string) => value ? new Date(value).toLocaleString("pt-BR") : "Em andamento";
export function EmployeeRoutesTab({employeeId,employeeName}:{employeeId:string;employeeName:string}) {
 const [clock]=useState(()=>Date.now());
 const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10));
 const [to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
 const [routes,setRoutes]=useState<Summary[]>([]),[detail,setDetail]=useState<WorkRoute|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[page,setPage]=useState(0);
 useEffect(()=>{const controller=new AbortController();let live=true;queueMicrotask(()=>{if(live){setLoading(true);setError("");}});fetch(`/api/work-routes?${new URLSearchParams({employeeId,from,to})}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(live){setRoutes(body.routes);if(body.truncated)setError("Consulta limitada. Reduza o período para ver todas as jornadas.");}}).catch(e=>{if(live&&e.name!=="AbortError")setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;controller.abort();};},[employeeId,from,to]);
 async function open(route:Summary){setError("");try{const response=await fetch(`/api/work-routes?${new URLSearchParams({employeeId,from,to,routeId:route.id})}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setDetail(body.routes[0]||null);setPage(0);}catch(e){setError(e instanceof Error?e.message:"Falha na consulta.");}}
 const points=detail?.points||[];const reliable=points.filter(p=>p.reliable);const lats=reliable.map(p=>p.latitude),lngs=reliable.map(p=>p.longitude);const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLng=Math.min(...lngs),maxLng=Math.max(...lngs);
 const projection=reliable.map(p=>`${20+(p.longitude-minLng)/Math.max(maxLng-minLng,.00001)*560},${220-(p.latitude-minLat)/Math.max(maxLat-minLat,.00001)*200}`).join(" ");
 return <section className="work-routes"><h3>Rotas & Localização • {employeeName}</h3><p>Histórico de trabalho, acesso restrito. Distância estimada por GPS; imprecisão e perda de sinal não comprovam conduta. Retenção: 90 dias.</p><div className="route-actions"><label>De <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{error&&<p role="alert">{error}</p>}{loading?<p>Consultando jornadas…</p>:routes.length===0?<p>Nenhuma rota registrada neste período.</p>:routes.map(route=><article key={route.id}><strong>{date(route.startedAt)} • {route.status==="active"?"Rota ativa":"Encerrada"}</strong><p>Fim: {date(route.endedAt)} • {route.distanceKm.toLocaleString("pt-BR")} km estimados • {route.stops.length} atendimentos • {route.pointCount} pontos</p><p>Último GPS: {date(route.lastPoint?.capturedAt)} • Precisão: {route.lastPoint?.accuracy.toFixed(0)||"—"} m</p>{route.status==="active"&&(!route.lastPoint||clock-Date.parse(route.lastPoint.capturedAt)>20*60000)&&<p>Sem atualização recente. Pode haver falta de sinal ou coleta interrompida.</p>}<button type="button" onClick={()=>void open(route)}>Ver percurso e paradas</button></article>)}{detail&&<article><div className="route-actions"><h4>Jornada de {date(detail.startedAt)}</h4><button onClick={()=>setDetail(null)}>Fechar percurso</button></div><p>Aviso confirmado: {date(detail.consentAt)} • Encerramento: {detail.closedReason||"—"}</p>{reliable.length>0&&<svg viewBox="0 0 600 240" role="img" aria-label="Traçado GPS esquemático sem mapa de ruas"><polyline points={projection} fill="none" stroke="#00a8e8" strokeWidth="3"/></svg>}<p>Traçado esquemático. Pontos com precisão superior a 100 m não compõem a distância; conexões no desenho não representam ruas.</p>{detail.stops.map(stop=><p key={stop.id}><b>{stop.osId} • {stop.customer}</b><br/>{stop.address}<br/>Chegada: {date(stop.arrivedAt)} • Saída: {date(stop.departedAt)} • Precisão: {stop.accuracy.toFixed(0)} m</p>)}<div className="route-table"><table><thead><tr><th>Horário GPS</th><th>Coordenadas</th><th>Precisão</th></tr></thead><tbody>{points.slice(page*50,(page+1)*50).map(p=><tr key={p.id}><td>{date(p.capturedAt)}</td><td>{p.latitude.toFixed(6)}, {p.longitude.toFixed(6)}</td><td>{p.accuracy.toFixed(0)} m {p.reliable?"":"• impreciso"}</td></tr>)}</tbody></table></div><div className="route-actions"><button disabled={!page} onClick={()=>setPage(page-1)}>Anterior</button><span>{page+1}/{Math.max(1,Math.ceil(points.length/50))}</span><button disabled={(page+1)*50>=points.length} onClick={()=>setPage(page+1)}>Próxima</button></div></article>}</section>;
}
