"use client";
import { useState } from "react";
import type { ErpRecord, OperationalCommand } from "@/lib/operational-ledger";
type Props = { mode: "Compras" | "Estoque"; modules: Record<string, ErpRecord[]>; onOperation: (command: OperationalCommand) => Promise<void> };
export function InventoryOperations({ mode, modules, onOperation }: Props) {
  const [selected, setSelected] = useState("");
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [productIds, setProductIds] = useState<Record<string, string>>({});
  const [type, setType] = useState("Entrada");
  const [reason, setReason] = useState("");
  const [sourceType, setSourceType] = useState("Estoque central");
  const [sourceId, setSourceId] = useState("");
  const [destinationType, setDestinationType] = useState("Estoque central");
  const [destinationId, setDestinationId] = useState("");
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  const products = modules.Produtos || [];
  const purchase = (modules.Compras || []).find(item => item.id === selected);
  const pending = (item: ErpRecord) => Number(item.quantity) - (purchase?.receiptHistory || []).reduce((sum: number, receipt: ErpRecord) => sum + (receipt.items || []).filter((line: ErpRecord) => line.itemId === item.id).reduce((total: number, line: ErpRecord) => total + Number(line.quantity),0),0);
  const submit = async () => {
    if (saving) return;
    setSaving(true);setNotice("");
    try {
      const command: OperationalCommand = mode === "Compras" ? { idempotencyKey: crypto.randomUUID(), action: "receive", recordId:selected, expectedRecord:purchase, data:{items:(purchase?.purchaseItems || []).filter((item:ErpRecord) => Number(quantities[item.id]) > 0).map((item:ErpRecord) => ({itemId:item.id,productId:item.productId || productIds[item.id],quantity:quantities[item.id]}))} } : type === "Transferência" ? { idempotencyKey:crypto.randomUUID(),action:"stock-transfer",data:{productId:selected,quantity:quantities.stock || 0,reason,sourceType,sourceId,sourceName:sourceId,destinationType,destinationId,destinationName:destinationId} } : { idempotencyKey:crypto.randomUUID(),action:"stock",data:{productId:selected,movementType:type,quantity:quantities.stock || 0,reason,destinationType,destinationId,destinationName:destinationId} };
      await onOperation(command);setNotice("Operação confirmada e registrada no livro de estoque.");setQuantities({});
    } catch(error) { setNotice(error instanceof Error ? error.message : "Falha ao registrar operação."); }
    finally { setSaving(false); }
  };
  return <section className="panel erp-card"><h3>{mode === "Compras" ? "Recebimento por item — parcial ou total" : "Livro de estoque e movimentos"}</h3><div className="settlement-form"><label>{mode === "Compras" ? "Compra" : "Produto"}<select value={selected} onChange={event => {setSelected(event.target.value);setQuantities({});setProductIds({});}}><option value="">Selecionar</option>{(mode === "Compras" ? (modules.Compras || []).filter(item => !/Cancelada|Recebida$/i.test(item.status || "")) : products).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{mode === "Compras" ? (purchase?.purchaseItems || []).filter((item:ErpRecord) => !["Serviço","Custo adicional"].includes(item.kind)).map((item:ErpRecord) => <div key={item.id} className="erp-receipt-line"><b>{item.description}</b><small>Pendente: {pending(item)}</small><label>Produto<select disabled={Boolean(item.productId)} value={item.productId || productIds[item.id] || ""} onChange={event => setProductIds(current => ({...current,[item.id]:event.target.value}))}><option value="">Vincular produto</option>{products.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Quantidade recebida<input type="number" min="0" max={pending(item)} step="0.001" value={quantities[item.id] || 0} onChange={event => setQuantities(current => ({...current,[item.id]:Number(event.target.value)}))}/></label></div>) : <><label>Tipo<select value={type} onChange={event => setType(event.target.value)}><option>Entrada</option><option>Saída</option><option>Ajuste</option><option>Transferência</option></select></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={quantities.stock || 0} onChange={event => setQuantities({stock:Number(event.target.value)})}/></label>{type==="Transferência"&&<><label>Origem<select value={sourceType} onChange={event=>{setSourceType(event.target.value);setSourceId("");}}>{["Estoque central","Veículo","Técnico","Obra","Casa / unidade","OS"].map(value=><option key={value}>{value}</option>)}</select></label><label>Identificação da origem<input value={sourceId} onChange={event=>setSourceId(event.target.value)} placeholder="Estoque, veículo, técnico, obra, casa ou OS"/></label></>}
<label>Destino<select value={destinationType} onChange={event=>{setDestinationType(event.target.value);setDestinationId("");}}>{["Estoque central","Veículo","Técnico","Obra","Casa / unidade","OS"].map(value=><option key={value}>{value}</option>)}</select></label>
<label>Identificação do destino{destinationType==="Técnico"?<select value={destinationId} onChange={event=>setDestinationId(event.target.value)}><option value="">Selecionar técnico</option>{(modules["Funcionários"]||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:destinationType==="Obra"?<select value={destinationId} onChange={event=>setDestinationId(event.target.value)}><option value="">Selecionar obra</option>{(modules.Obras||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:destinationType==="OS"?<input value={destinationId} onChange={event=>setDestinationId(event.target.value)} placeholder="Código da OS"/>:<input value={destinationId} onChange={event=>setDestinationId(event.target.value)} placeholder={destinationType==="Estoque central"?"Estoque principal":"Veículo, casa, unidade ou referência"}/>}</label>
<label>Motivo<textarea value={reason} onChange={event => setReason(event.target.value)}/></label><small>Entradas e saídas alteram o saldo total. Transferências apenas movimentam a localização do material e preservam o saldo global, mantendo origem e destino rastreáveis.</small></>}</div><button className="primary-btn" disabled={saving || !selected} onClick={() => void submit()}>{saving ? "Confirmando..." : "Confirmar no banco"}</button>{notice && <p role="status">{notice}</p>}{mode === "Estoque" && <div className="w-full overflow-x-auto min-w-0 table-wrap"><table><thead><tr><th>DATA</th><th>PRODUTO</th><th>TIPO</th><th>QUANTIDADE</th><th>ORIGEM</th><th>DESTINO</th><th>USUÁRIO / MOTIVO</th></tr></thead><tbody>{[...(modules["Livro de estoque"] || [])].reverse().map(item => <tr key={item.id}><td>{item.createdAt?.slice(0,10)}</td><td>{products.find(product => product.id === item.productId)?.name || item.productId}</td><td>{item.kind}</td><td>{item.transferQuantity ?? item.quantity}</td><td>{item.sourceType ? `${item.sourceType}${item.sourceName || item.sourceId ? ` • ${item.sourceName || item.sourceId}` : ""}` : item.purchaseId || item.receiptId || "Manual / abertura"}</td><td>{item.destinationType || "Estoque"}{item.destinationName || item.destinationId ? ` • ${item.destinationName || item.destinationId}` : ""}</td><td>{item.user} • {item.reason}</td></tr>)}</tbody></table></div>}</section>;
}
