"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";

type Company={id:string;trade_name?:string;legal_name?:string;billing_auto_block?:boolean;billing_grace_days?:number};
type Receivable={id:string;company_id:string;description:string;amount:number;due_date:string;status:"open"|"paid"|"cancelled";computed_status?:"open"|"overdue"|"paid"|"cancelled";paid_at?:string|null};
type FinancialSummary={companyId:string;blocked:boolean;autoBlock:boolean;graceDays:number;overdueCount:number;overdueAmount:number;daysOverdue:number};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0));

export function ManagerReceivables(){
 const[companies,setCompanies]=useState<Company[]>([]);const[receivables,setReceivables]=useState<Receivable[]>([]);const[summary,setSummary]=useState<FinancialSummary[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[setupPending,setSetupPending]=useState(false);
 const[companyId,setCompanyId]=useState("");const[amount,setAmount]=useState("");const[dueDate,setDueDate]=useState("");const[description,setDescription]=useState("Mensalidade ProAR");
 const companyMap=useMemo(()=>Object.fromEntries(companies.map(item=>[item.id,item])),[companies]);const financialMap=useMemo(()=>Object.fromEntries(summary.map(item=>[item.companyId,item])),[summary]);
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/manager/receivables",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao carregar contas a receber.");setCompanies(j.companies||[]);setReceivables(j.receivables||[]);setSummary(j.financialSummary||[]);setSetupPending(Boolean(j.setupPending));if(!companyId&&j.companies?.[0]?.id)setCompanyId(j.companies[0].id);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar contas a receber.");}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent)=>{e.preventDefault();const r=await fetch("/api/manager/receivables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId,amount:Number(amount.replace(",",".")),dueDate,description})});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao criar conta.");return}setAmount("");setDueDate("");setDescription("Mensalidade ProAR");void load()};
 const update=async(item:Receivable,status:"paid"|"cancelled")=>{const body:any={id:item.id,companyId:item.company_id,status};if(status==="paid")body.paymentMethod=window.prompt("Forma de pagamento:","PIX")||"";const r=await fetch("/api/manager/receivables",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao atualizar conta.");return}void load()};
 const settings=async(company:Company)=>{const state=financialMap[company.id];const grace=window.prompt("Dias de tolerância após o vencimento:",String(state?.graceDays??company.billing_grace_days??5));if(grace===null)return;const autoBlock=window.confirm("OK = bloqueio automático ativo. Cancelar = desativado.");const r=await fetch("/api/manager/receivables",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({updateBillingSettings:true,companyId:company.id,graceDays:Number(grace||0),autoBlock})});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao atualizar regra.");return}void load()};
 const totals=useMemo(()=>({open:receivables.filter(i=>i.computed_status==="open").reduce((s,i)=>s+Number(i.amount||0),0),overdue:receivables.filter(i=>i.computed_status==="overdue").reduce((s,i)=>s+Number(i.amount||0),0),paid:receivables.filter(i=>i.status==="paid").reduce((s,i)=>s+Number(i.amount||0),0),blocked:summary.filter(i=>i.blocked).length}),[receivables,summary]);
 return <section className="manager-panel manager-receivables"><div className="panel-head"><div><h2>Contas a receber</h2><p>Mensalidades do ProAR, baixa de pagamentos e bloqueio financeiro automático.</p></div><button onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button></div>
 {error&&<div className="manager-alert">{error}</div>}{setupPending&&<div className="manager-alert">A estrutura de contas a receber ainda não foi aplicada no banco mestre. O bloqueio financeiro permanece inativo.</div>}
 <div className="manager-billing-summary"><article><b>{money(totals.open)}</b><span>A vencer</span></article><article><b>{money(totals.overdue)}</b><span>Vencido</span></article><article><b>{money(totals.paid)}</b><span>Recebido</span></article><article><b>{totals.blocked}</b><span>Bloqueadas</span></article></div>
 <form className="manager-receivable-form" onSubmit={create}><label>Empresa<select value={companyId} onChange={e=>setCompanyId(e.target.value)} required><option value="">Selecione</option>{companies.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.legal_name}</option>)}</select></label><label>Descrição<input value={description} onChange={e=>setDescription(e.target.value)} required/></label><label>Valor<input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required/></label><label>Vencimento<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></label><button disabled={loading||setupPending}>Criar conta</button></form>
 <div className="manager-billing-companies">{companies.map(c=>{const st=financialMap[c.id];return <article key={c.id} className={st?.blocked?"blocked":""}><div><b>{c.trade_name||c.legal_name}</b><small>{st?.blocked?"BLOQUEIO FINANCEIRO ATIVO":st?.overdueCount?String(st.overdueCount)+" conta(s) vencida(s)":"Em dia"}</small></div><span>{money(st?.overdueAmount||0)} vencido</span><span>{st?.graceDays??c.billing_grace_days??5} dias de tolerância</span><button onClick={()=>void settings(c)}>Regra de cobrança</button></article>})}</div>
 <div className="manager-receivable-table"><div className="head"><span>Empresa</span><span>Descrição</span><span>Vencimento</span><span>Valor</span><span>Status</span><span>Ações</span></div>{receivables.map(i=><div className="row" key={i.id}><span>{companyMap[i.company_id]?.trade_name||companyMap[i.company_id]?.legal_name||i.company_id}</span><span>{i.description}</span><span>{new Date(i.due_date+"T12:00:00").toLocaleDateString("pt-BR")}</span><span>{money(i.amount)}</span><span className={i.computed_status||i.status}>{i.status==="paid"?"Pago":i.status==="cancelled"?"Cancelado":i.computed_status==="overdue"?"Vencido":"Aberto"}</span><span>{i.status==="open"?<><button onClick={()=>void update(i,"paid")}>Baixar</button><button onClick={()=>void update(i,"cancelled")}>Cancelar</button></>:i.paid_at?new Date(i.paid_at).toLocaleDateString("pt-BR"):"—"}</span></div>)}</div>
 </section>;
}