"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, DatabaseBackup, Gauge, Globe2, LifeBuoy, ShieldAlert, Wrench } from "lucide-react";

type Company={id:string;trade_name?:string;legal_name?:string;slug?:string;plan_code?:string;status?:string};
type Control={company_id:string;maintenance_enabled?:boolean;maintenance_message?:string;support_access_enabled?:boolean;support_access_until?:string|null;support_access_reason?:string|null;custom_domain?:string|null;domain_status?:string;feature_flags?:Record<string,boolean>;limit_overrides?:Record<string,number>;backup_status?:string;last_backup_at?:string|null;backup_retention_days?:number;rollout_channel?:"pilot"|"staged"|"general";target_version?:string|null};
type Incident={id:string;company_id?:string;severity:string;status:string;title:string;description?:string;code?:string;created_at?:string};
type Usage={available:boolean;users?:number;serviceOrders?:number;customers?:number;equipment?:number;products?:number;limits?:{users:number;serviceOrdersPerMonth:number;storageGb:number;aiCallsPerMonth:number}};
type Alert={type:string;companyId?:string;severity:string;title:string;detail?:string};
type Job={id:string;company_id?:string;job_type:string;status:string;requested_by?:string;requested_at?:string;details?:Record<string,unknown>};

export function ManagerControlCenter(){
 const[companies,setCompanies]=useState<Company[]>([]);const[controls,setControls]=useState<Control[]>([]);const[incidents,setIncidents]=useState<Incident[]>([]);const[alerts,setAlerts]=useState<Alert[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[selectedId,setSelectedId]=useState("");const[usage,setUsage]=useState<Usage|null>(null);const[setupPending,setSetupPending]=useState(false);const[error,setError]=useState("");
 const selected=companies.find(c=>c.id===selectedId)||null;const control=controls.find(c=>c.company_id===selectedId)||null;
 const load=async()=>{setError("");try{const r=await fetch("/api/manager/control-center",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao carregar Centro Operacional.");setCompanies(j.companies||[]);setControls(j.controls||[]);setIncidents(j.incidents||[]);setAlerts(j.alerts||[]);setJobs(j.jobs||[]);setSetupPending(Boolean(j.setupPending));if(!selectedId&&j.companies?.[0]?.id)setSelectedId(j.companies[0].id);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar Centro Operacional.");}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selectedId){setUsage(null);return}fetch("/api/manager/control-center?companyId="+encodeURIComponent(selectedId),{cache:"no-store"}).then(async r=>r.ok?r.json():null).then(j=>{if(j){setUsage(j.usage||null);if(j.controls)setControls(cur=>[...cur.filter(x=>x.company_id!==selectedId),...(j.controls||[])]);if(j.jobs)setJobs(cur=>[...cur.filter(x=>x.company_id!==selectedId),...(j.jobs||[])]);}}).catch(()=>{})},[selectedId]);
 const save=async(body:Record<string,unknown>)=>{if(!selectedId)return;const r=await fetch("/api/manager/control-center",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:selectedId,...body})});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao atualizar.");return}void load()};
 const action=async(name:string)=>{if(!selectedId)return;const r=await fetch("/api/manager/control-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:selectedId,action:name})});const j=await r.json();if(!r.ok){setError(j.error||"Falha na ação.");return}if(j.message)window.alert(j.message);void load()};
 const createIncident=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const r=await fetch("/api/manager/control-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createIncident",companyId:selectedId,title:String(form.get("title")||""),description:String(form.get("description")||""),severity:String(form.get("severity")||"warning"),source:"manager"})});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao registrar incidente.");return}e.currentTarget.reset();void load()};
 const resolveIncident=async(id:string)=>{const r=await fetch("/api/manager/control-center",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({resolveIncident:true,incidentId:id})});if(r.ok)void load()};
 const openIncidents=useMemo(()=>incidents.filter(i=>i.status==="open"&&(!selectedId||i.company_id===selectedId)),[incidents,selectedId]);
 return <section className="manager-panel manager-control-center"><div className="panel-head"><div><h2>Centro Operacional SaaS</h2><p>Manutenção, rollout, domínio, suporte, limites, backups e incidentes por empresa.</p></div></div>
 {error&&<div className="manager-alert">{error}</div>}{setupPending&&<div className="manager-alert">A migration do Centro Operacional ainda não foi aplicada no banco mestre. Os controles permanecem em modo somente preparação.</div>}
 <div className="manager-control-toolbar"><label>Empresa<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Selecione</option>{companies.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.legal_name}</option>)}</select></label>{selected&&<span>{selected.slug||selected.id} • {selected.plan_code||"trial"}</span>}</div>
 <div className="manager-control-grid">
  <article><header><Wrench size={17}/><b>Modo manutenção</b></header><label className="switch-line"><input type="checkbox" checked={Boolean(control?.maintenance_enabled)} onChange={e=>void save({maintenanceEnabled:e.target.checked})}/><span>Bloquear acesso temporariamente</span></label><textarea value={control?.maintenance_message||"Sistema em manutenção. Tente novamente mais tarde."} onChange={e=>setControls(cur=>[...cur.filter(x=>x.company_id!==selectedId),{...(control||{company_id:selectedId}),maintenance_message:e.target.value}])}/><button onClick={()=>void save({maintenanceMessage:control?.maintenance_message||""})}>Salvar mensagem</button></article>
  <article><header><Gauge size={17}/><b>Feature flags</b></header>{["diagnosticoIA","fiscalNovo","mobileNovo","betaFeatures"].map(flag=><label className="switch-line" key={flag}><input type="checkbox" checked={Boolean(control?.feature_flags?.[flag])} onChange={e=>void save({featureFlags:{[flag]:e.target.checked}})}/><span>{flag}</span></label>)}</article>
  <article><header><Globe2 size={17}/><b>Domínio</b></header><input placeholder="cliente.com.br" value={control?.custom_domain||""} onChange={e=>setControls(cur=>[...cur.filter(x=>x.company_id!==selectedId),{...(control||{company_id:selectedId}),custom_domain:e.target.value}])}/><div className="inline-actions"><button onClick={()=>void save({customDomain:control?.custom_domain||""})}>Salvar</button><button onClick={()=>void action("verifyDomain")}>Verificar</button></div><small>Status: {control?.domain_status||"não configurado"}</small></article>
  <article><header><DatabaseBackup size={17}/><b>Backup</b></header><span>Status: {control?.backup_status||"não solicitado"}</span><span>Último: {control?.last_backup_at?new Date(control.last_backup_at).toLocaleString("pt-BR"):"—"}</span><label>Retenção (dias)<input type="number" min={1} max={3650} value={control?.backup_retention_days||30} onChange={e=>void save({backupRetentionDays:Number(e.target.value)})}/></label><button onClick={()=>void action("requestBackup")}>Solicitar backup</button></article>
  <article><header><LifeBuoy size={17}/><b>Suporte</b></header><label className="switch-line"><input type="checkbox" checked={Boolean(control?.support_access_enabled)} onChange={e=>void save({supportAccessEnabled:e.target.checked,supportAccessReason:control?.support_access_reason||"Suporte autorizado pelo Manager"})}/><span>Permitir suporte ProAR por 60 min</span></label><input placeholder="Motivo do acesso" value={control?.support_access_reason||""} onChange={e=>setControls(cur=>[...cur.filter(x=>x.company_id!==selectedId),{...(control||{company_id:selectedId}),support_access_reason:e.target.value}])}/><button onClick={()=>void save({supportAccessReason:control?.support_access_reason||""})}>Salvar motivo</button><button onClick={()=>void action("runDiagnostic")}>Executar diagnóstico</button><small>{control?.support_access_until?"Expira: "+new Date(control.support_access_until).toLocaleString("pt-BR"):"Acesso de suporte desativado."}</small></article>
  <article><header><Gauge size={17}/><b>Uso e limites</b></header>{usage?.available?<><span>Usuários: {usage.users} / {control?.limit_overrides?.users??usage.limits?.users}</span><span>OS: {usage.serviceOrders} / {control?.limit_overrides?.serviceOrdersPerMonth??usage.limits?.serviceOrdersPerMonth}</span><span>Clientes: {usage.customers}</span><span>Equipamentos: {usage.equipment}</span><span>Produtos: {usage.products}</span><label>Limite usuários<input type="number" min={1} value={control?.limit_overrides?.users??usage.limits?.users??1} onChange={e=>void save({limitOverrides:{users:Number(e.target.value)}})}/></label><label>Limite OS/mês<input type="number" min={1} value={control?.limit_overrides?.serviceOrdersPerMonth??usage.limits?.serviceOrdersPerMonth??1} onChange={e=>void save({limitOverrides:{serviceOrdersPerMonth:Number(e.target.value)}})}/></label></>:<span>Uso não disponível para este tenant.</span>}</article>
   <article><header><Gauge size={17}/><b>Rollout</b></header><label>Canal<select value={control?.rollout_channel||"general"} onChange={e=>void save({rolloutChannel:e.target.value})}><option value="pilot">Piloto</option><option value="staged">Gradual</option><option value="general">Geral</option></select></label><label>Versão alvo<input value={control?.target_version||""} placeholder="Ex.: 3.2.0" onChange={e=>setControls(cur=>[...cur.filter(x=>x.company_id!==selectedId),{...(control||{company_id:selectedId}),target_version:e.target.value}])}/></label><button onClick={()=>void save({targetVersion:control?.target_version||""})}>Salvar rollout</button><small>Use Piloto para PolarTech, Gradual para grupos controlados e Geral para clientes estáveis.</small></article>
 </div>
 <div className="manager-alerts-box"><h3><ShieldAlert size={17}/> Alertas do Manager</h3>{alerts.length?alerts.slice(0,12).map((a,i)=><div key={i} className={"alert "+a.severity}><b>{a.title}</b><span>{a.detail||a.companyId||"Plataforma"}</span></div>):<p>Nenhum alerta operacional registrado.</p>}</div>
 <div className="manager-incidents"><div><h3><AlertTriangle size={17}/> Incidentes</h3><form onSubmit={createIncident}><input name="title" placeholder="Título do incidente" required/><select name="severity" defaultValue="warning"><option value="info">Informação</option><option value="warning">Atenção</option><option value="error">Erro</option><option value="critical">Crítico</option></select><input name="description" placeholder="Descrição"/><button>Registrar</button></form></div><div>{openIncidents.map(i=><article key={i.id}><div><b>{i.title}</b><small>{i.code||i.severity} • {i.created_at?new Date(i.created_at).toLocaleString("pt-BR"):""}</small><span>{i.description||""}</span></div><button onClick={()=>void resolveIncident(i.id)}>Resolver</button></article>)}{!openIncidents.length&&<p>Nenhum incidente aberto para a seleção atual.</p>}</div></div>
 <div className="manager-lifecycle"><h3>Ciclo de vida do tenant</h3><div className="inline-actions"><button onClick={()=>void action("createTestEnvironment")}>Criar homologação</button><button onClick={()=>void action("requestExport")}>Solicitar exportação</button><button onClick={()=>void action("requestRestore")}>Solicitar restauração</button><button onClick={()=>void action("requestTermination")}>Solicitar encerramento</button><button onClick={()=>void action("requestArchive")}>Solicitar arquivamento</button></div><small>Essas ações são registradas em fila auditável e não alteram nem apagam dados automaticamente.</small><div className="manager-jobs">{jobs.filter(job=>!selectedId||job.company_id===selectedId).slice(0,10).map(job=><article key={job.id}><b>{job.job_type}</b><span>{job.status}</span><small>{job.requested_at?new Date(job.requested_at).toLocaleString("pt-BR"):"—"} • {job.requested_by||"Sistema"}</small></article>)}{!jobs.filter(job=>!selectedId||job.company_id===selectedId).length&&<p>Nenhum job administrativo registrado.</p>}</div></div>
 </section>;
}