"use client";
import {useEffect,useRef,useState} from "react";
import type {WorkRoute,RouteCommand} from "@/lib/work-routes";
import "./work-routes.css";
type NativeRoute={position:()=>Promise<NonNullable<RouteCommand["points"]>[number]>;start:(options:{routeId:string;expiresAt:string;username:string})=>Promise<unknown>;stop:()=>Promise<unknown>;sync:()=>Promise<unknown>;status:()=>Promise<{active:boolean;pending:number;error?:string}>};
function nativeRoute():NativeRoute|null{const cap=(window as unknown as {Capacitor?:{isNativePlatform?:()=>boolean;isPluginAvailable?:(name:string)=>boolean;nativePromise?:(plugin:string,method:string,options:unknown)=>Promise<unknown>}}).Capacitor;if(!cap?.isNativePlatform?.()||!cap.nativePromise||!cap.isPluginAvailable?.("WorkRoute"))return null;const invoke=(method:string,options:unknown={})=>cap.nativePromise!("WorkRoute",method,options);return {position:()=>invoke("position") as ReturnType<NativeRoute["position"]>,start:options=>invoke("start",options),stop:()=>invoke("stop"),sync:()=>invoke("sync"),status:()=>invoke("status") as ReturnType<NativeRoute["status"]>};}
type Data={employee?:{employeeId:string;employeeName:string;username:string};routes:(WorkRoute&{lastPoint?:WorkRoute["points"][number]})[];orders:{id:string;client:string;status:string}[]};
const gps=()=>new Promise<NonNullable<RouteCommand["points"]>[number]>((resolve,reject)=>navigator.geolocation.getCurrentPosition(position=>resolve({id:crypto.randomUUID(),capturedAt:new Date(position.timestamp).toISOString(),latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}));
async function command(body:RouteCommand){const response=await fetch("/api/work-routes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Falha ao salvar rota.");return data;}
export function MobileRouteControls(){
 const [foreground,setForeground]=useState(false);
 const [data,setData]=useState<Data|null>(null),[consent,setConsent]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[os,setOs]=useState(""),[nativeState,setNativeState]=useState<{active:boolean;pending:number;error?:string}|null>(null);
 const flight=useRef<NonNullable<RouteCommand["points"]>|null>(null);
 const watch=useRef<number|null>(null),last=useRef(0),pending=useRef<NonNullable<RouteCommand["points"]>>([]),sending=useRef(false);
 const active=data?.routes.find(route=>route.status==="active");
 async function refresh(){try{const response=await fetch("/api/work-routes",{cache:"no-store"});if(response.status===401){setData(null);if(watch.current!==null){navigator.geolocation.clearWatch(watch.current);watch.current=null;}await nativeRoute()?.stop();return;}const body=await response.json();if(!response.ok){setError(body.error);return;}setData(body);const native=nativeRoute();if(native){await native.sync();setNativeState(await native.status());}}catch{setError("Sem conexão. O Android conserva pontos pendentes por até 24 horas.");}}
 useEffect(()=>{void Promise.resolve().then(refresh);const interval=setInterval(()=>void refresh(),30000);return()=>{clearInterval(interval);if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);};},[]);
 async function flush(routeId:string){if(sending.current||!pending.current.length)return;sending.current=true;const batch=flight.current||pending.current.slice(0,50);flight.current=batch;try{await command({action:"points",routeId,requestId:batch[0].id,points:batch});pending.current.splice(0,batch.length);flight.current=null;}finally{sending.current=false;}}
 function watchForeground(route:WorkRoute){if(watch.current!==null)return;setForeground(true);watch.current=navigator.geolocation.watchPosition(position=>{if(Date.now()>Date.parse(route.expiresAt)){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setForeground(false);setError("Jornada expirada. Encerre a rota.");return;}if(Date.now()-last.current<60000)return;last.current=Date.now();pending.current.push({id:crypto.randomUUID(),capturedAt:new Date(position.timestamp).toISOString(),latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy});if(pending.current.length>720){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setForeground(false);setError("Limite local atingido. Reconecte para sincronizar.");return;}void flush(route.id).catch(e=>setError(e.message));},e=>setError(e.message),{enableHighAccuracy:true,maximumAge:10000,timeout:20000});}
 async function run(action:()=>Promise<void>){setBusy(true);setError("");try{await action();await refresh();}catch(e){setError(e instanceof Error?e.message:"Operação indisponível.");}finally{setBusy(false);}}
 async function start(){const saved=await command({action:"start",requestId:crypto.randomUUID(),consent:true});const route=saved.route as WorkRoute;const native=nativeRoute();try{if(native)await native.start({routeId:route.id,expiresAt:route.expiresAt,username:data?.employee?.username||""});else{await gps();watchForeground(route);}}catch(e){await command({action:"finish",routeId:route.id,requestId:crypto.randomUUID(),reason:"Coleta não iniciada: permissão GPS indisponível"});throw e;}}
 async function finish(){if(!active)return;setForeground(false);if(watch.current!==null){navigator.geolocation.clearWatch(watch.current);watch.current=null;}const native=nativeRoute();if(native){await native.stop();await native.sync();}else{await flush(active.id);if(pending.current.length)throw new Error("Há pontos aguardando envio. Reconecte e tente encerrar novamente.");await command({action:"finish",routeId:active.id,requestId:crypto.randomUUID()});}}
 if(!data?.employee)return null;
 return <section className="work-routes route-mobile"><div className="route-status-head"><div><small>JORNADA E LOCALIZAÇÃO</small><h3>Minha Rota • {data.employee.employeeName}</h3></div><span className={active&&(nativeState?.active||foreground)?"route-live":"route-off"}>{active&&(nativeState?.active||foreground)?"GPS ATIVO":"GPS INATIVO"}</span></div>{active?<><p><b>{nativeState?.active||foreground?"Localização de trabalho ativa":"Jornada aberta; coleta pausada"}</b> • Início: {new Date(active.startedAt).toLocaleString("pt-BR")}</p><p>Coleta a cada minuto, somente nesta jornada (máximo 12h). Histórico acessível somente a gestores autorizados por 90 dias. O colaborador vê nesta tela quando a coleta está ativa.</p>{!nativeRoute()&&<p>Navegador/PWA: coleta apenas enquanto esta tela permanece aberta. Pontos offline ficam na memória e podem ser perdidos ao fechar.</p>}{nativeState&&<p>{nativeState.pending} pontos aguardando sincronização. {nativeState.error||""}</p>}<div className="route-actions"><button disabled={busy} onClick={()=>void run(async()=>{const native=nativeRoute();if(native)await native.start({routeId:active.id,expiresAt:active.expiresAt,username:data.employee!.username});else watchForeground(active);})}>Retomar coleta</button><button disabled={busy} onClick={()=>void run(finish)}>Encerrar rota</button></div><div className="route-actions"><select aria-label="OS para check-in" value={os} onChange={e=>setOs(e.target.value)}><option value="">Selecione a OS atribuída</option>{data.orders.map(order=><option key={order.id} value={order.id}>{order.id} • {order.client}</option>)}</select><button disabled={busy||!os} onClick={()=>void run(async()=>{const point=await (nativeRoute()?.position()||gps());await command({action:"checkin",routeId:active.id,requestId:crypto.randomUUID(),osId:os,points:[point]});})}>Check-in</button><button disabled={busy||!active.stops.some(stop=>!stop.departedAt)} onClick={()=>void run(async()=>{const point=await (nativeRoute()?.position()||gps());await command({action:"checkout",routeId:active.id,requestId:crypto.randomUUID(),points:[point]});})}>Saída da OS</button></div></>:<><p>Ao iniciar, o Android registra localização durante a rota, mesmo com a tela bloqueada, e mostra uma notificação. Encerrar interrompe a coleta. Pontos pendentes são guardados no aparelho por até 24h; histórico restrito por 90 dias. O navegador coleta somente com a tela aberta.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Li o aviso e desejo iniciar a localização de trabalho nesta jornada.</label><div className="route-actions"><button disabled={!consent||busy} onClick={()=>void run(start)}>Iniciar rota</button></div></>}{error&&<p role="alert">{error}</p>}</section>;
}
