"use client";
import {useEffect,useMemo,useState,type ElementType} from "react";
import {Activity,Bot,ClipboardCheck,ExternalLink,FileText,Gavel,Radar,RefreshCw,ShieldAlert} from "lucide-react";
type Opportunity={canonicalId:string;pncpId?:string;source:string;sourceUrl?:string;buyerName?:string;buyerCnpj?:string;city?:string;state?:string;modality?:string;processNumber?:string;object:string;estimatedValue?:number;proposalEndAt?:string;distanceKm?:number;score:number};
type Source={id:string;name:string;base_url:string;integration_mode:string;status:string;enabled?:boolean;health_message?:string;last_success_at?:string};
type Check={key:string;label:string;result:"ok"|"attention"|"blocker"|"not_applicable";detail:string;action:string};
const money=(value?:number)=>Number(value??0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),date=(value?:string)=>value?new Date(value).toLocaleString("pt-BR"):"Não informado";
export function ProcurementWorkspace(){
  const[tab,setTab]=useState<"radar"|"preflight"|"documents"|"bids"|"sources">("radar"),[items,setItems]=useState<Opportunity[]>([]),[sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState<Opportunity|null>(null),[checks,setChecks]=useState<Check[]>([]),[warning,setWarning]=useState(""),[loading,setLoading]=useState(false),[bid,setBid]=useState({amount:"",cost:"",minimumAuthorized:"",taxRate:""}),[simulation,setSimulation]=useState<{result:number;margin:number;belowMinimum:boolean;copyValue:string}|null>(null);
  const loadRadar=async()=>{setLoading(true);try{const response=await fetch("/api/procurement/radar?radius=300"),json=await response.json();setItems(json.data??[]);setWarning(json.warning??json.error??"");}catch{setWarning("Não foi possível atualizar o Radar agora.");}finally{setLoading(false);}};
  const loadSources=async()=>{const response=await fetch("/api/procurement/sources"),json=await response.json();setSources(json.data??[]);};
  useEffect(()=>{void loadRadar();void loadSources();},[]);
  const summary=useMemo(()=>({today:items.filter(item=>item.proposalEndAt&&new Date(item.proposalEndAt).getTime()>Date.now()).length,priorityA:items.filter(item=>item.score>=80).length,deadline:items.filter(item=>item.proposalEndAt&&new Date(item.proposalEndAt).getTime()-Date.now()<=48*3600000).length}),[items]);
  const runPreflight=async(opportunity:Opportunity)=>{setSelected(opportunity);setTab("preflight");const response=await fetch("/api/procurement/preflight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({canonicalId:opportunity.canonicalId})}),json=await response.json();setChecks(json.data?.checks??[]);};
  const simulate=async()=>{const response=await fetch("/api/procurement/bids/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:Number(bid.amount),cost:Number(bid.cost),minimumAuthorized:Number(bid.minimumAuthorized),taxRate:Number(bid.taxRate)})}),json=await response.json();setSimulation(json.data??null);};
  const tabs:Array<{id:typeof tab;label:string;Icon:ElementType}>=[{id:"radar",label:"Radar",Icon:Radar},{id:"preflight",label:"Auditoria pré-envio",Icon:ClipboardCheck},{id:"documents",label:"Documentos",Icon:FileText},{id:"bids",label:"Copiloto de lances",Icon:Gavel},{id:"sources",label:"Saúde das fontes",Icon:Activity}];
  return <section className="panel" style={{marginBottom:18}}>
    <header className="public-contracts-head"><div><span className="section-kicker"><Radar size={13}/> LICITAÇÕES IA</span><h2>Radar e Bid Agent</h2><p>Descoberta, análise, pré-envio e decisão de lances em um único workspace.</p></div><button className="outline-btn" onClick={()=>void loadRadar()} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>{loading?"Atualizando...":"Atualizar Radar"}</button></header>
    <nav style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}>{tabs.map(({id,label,Icon})=><button key={id} className={tab===id?"primary-btn":"outline-btn"} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</nav>
    {tab==="radar"&&<><div className="public-contract-kpis"><article><small>NOVAS / ABERTAS</small><strong>{summary.today}</strong></article><article><small>PRIORIDADE A</small><strong>{summary.priorityA}</strong></article><article><small>ABERTURA EM 48H</small><strong>{summary.deadline}</strong></article><article><small>FONTES ATIVAS</small><strong>{sources.filter(source=>source.enabled!==false).length}</strong></article></div>{warning&&<p className="public-contract-message"><ShieldAlert size={15}/>{warning}</p>}<div style={{overflowX:"auto"}}><table className="procurement-table"><thead><tr><th>Score</th><th>Órgão / cidade</th><th>Objeto</th><th>Modalidade</th><th>Valor</th><th>Abertura</th><th>Fonte</th><th>Ação</th></tr></thead><tbody>{items.map(item=><tr key={item.canonicalId}><td><b className={item.score>=80?"score-a":item.score>=60?"score-b":"score-c"}>{item.score}</b></td><td>{item.buyerName||"Órgão não informado"}<small>{item.city}{item.state?`/${item.state}`:""}{item.distanceKm!==undefined?` • ${item.distanceKm} km`:""}</small></td><td>{item.object}</td><td>{item.modality||"Não informada"}</td><td>{money(item.estimatedValue)}</td><td>{date(item.proposalEndAt)}</td><td>{item.source}</td><td><button className="outline-btn" onClick={()=>void runPreflight(item)}>Analisar</button>{item.sourceUrl&&<a className="outline-btn" href={item.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a>}</td></tr>)}</tbody></table></div>{!loading&&!items.length&&<p className="linked-empty">Nenhuma oportunidade normalizada disponível nesta prévia.</p>}</>}
    {tab==="preflight"&&<div className="procurement-preflight"><h3>Auditoria pré-envio {selected?`• ${selected.processNumber||selected.canonicalId}`:""}</h3><p>O status “Pronta para envio” é calculado exclusivamente no backend.</p>{!selected?<p>Selecione uma oportunidade no Radar para iniciar a auditoria.</p>:<>{checks.map(check=><article key={check.key} className={`preflight-${check.result}`}><b>{check.result==="ok"?"🟢":check.result==="blocker"?"🔴":"🟠"} {check.label}</b><span>{check.detail}</span><small>{check.action}</small></article>)}<button className="primary-btn" onClick={()=>void runPreflight(selected)}><ClipboardCheck size={15}/> Recalcular auditoria</button></>}</div>}
    {tab==="documents"&&<div className="linked-empty"><FileText size={22}/><h3>Cofre de documentos</h3><p>Documentos, validades e evidências serão vinculados ao processo após a migration, sem substituir arquivos existentes.</p></div>}
    {tab==="bids"&&<div className="procurement-bid"><h3><Bot size={18}/> Copiloto de lances</h3><p>Simula margem e limite. A única ação externa é copiar o valor; nenhum lance é enviado automaticamente.</p><div className="public-contract-fields"><label>Valor do lance<input type="number" value={bid.amount} onChange={event=>setBid({...bid,amount:event.target.value})}/></label><label>Custo total<input type="number" value={bid.cost} onChange={event=>setBid({...bid,cost:event.target.value})}/></label><label>Limite autorizado<input type="number" value={bid.minimumAuthorized} onChange={event=>setBid({...bid,minimumAuthorized:event.target.value})}/></label><label>Tributos (%)<input type="number" value={bid.taxRate} onChange={event=>setBid({...bid,taxRate:event.target.value})}/></label></div><button className="primary-btn" onClick={()=>void simulate()}>Simular lance</button>{simulation&&<div className={simulation.belowMinimum?"preflight-blocker":"preflight-ok"}><b>{simulation.belowMinimum?"⛔ LANCE ABAIXO DO LIMITE AUTORIZADO":"🟢 Dentro do limite autorizado"}</b><span>Resultado: {money(simulation.result)} • Margem: {simulation.margin.toFixed(2)}%</span><button className="outline-btn" onClick={()=>navigator.clipboard?.writeText(simulation.copyValue)}>Copiar valor {simulation.copyValue}</button></div>}</div>}
    {tab==="sources"&&<div className="procurement-sources">{sources.map(source=><article key={source.id}><div><b>{source.name}</b><small>{source.integration_mode}</small></div><span className={`source-${source.status}`}>{source.status}</span><p>{source.health_message||"Sem mensagem."}</p><small>Último sucesso: {date(source.last_success_at)}</small><a href={source.base_url} target="_blank" rel="noreferrer">Abrir fonte oficial <ExternalLink size={13}/></a></article>)}</div>}
  </section>;
}
