"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, FileText, Plus, ShieldCheck, ThermometerSnowflake, UserRoundCheck } from "lucide-react";
import { nextPmocDate, refrigerantAvailable, retrofitEstimate, type PmocPlan, type Refrigerant, type TechnicalDocument } from "@/lib/technical-compliance";

type Props={ plans:PmocPlan[]; fluids:Refrigerant[]; documents:TechnicalDocument[]; onSave:(module:string,record:any)=>Promise<boolean>|void };
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function TechnicalCompliancePanel({plans,fluids,documents,onSave}:Props){
  const [tab,setTab]=useState<"PMOC"|"Retrofit"|"Refrigerantes"|"Habilitação">("PMOC");
  const [retrofit,setRetrofit]=useState({investment:0,currentKw:0,proposedKw:0,hoursPerMonth:220,tariff:1});
  const estimate=useMemo(()=>retrofitEstimate(retrofit),[retrofit]);
  const soon=documents.filter(item=>item.expiresAt&&new Date(item.expiresAt)<=new Date(Date.now()+30*864e5)).length;
  const scheduled=plans.filter(p=>nextPmocDate(p)).length;
  const documented=plans.filter(p=>p.technicalResponsible).length;
  const pending=Math.max(0,plans.length-documented);
  return <section className="customer-panel technical-compliance-panel pmoc-workspace">
    <div className="panel-head pmoc-hero"><div><span className="section-kicker"><ShieldCheck size={12}/> CONFORMIDADE TÉCNICA</span><h2>PMOC e conformidade</h2><p>Planeje manutenções, acompanhe responsáveis técnicos, refrigerantes e documentos em um único fluxo.</p></div><button className="primary-btn" onClick={()=>onSave("PMOC",{id:`PMOC-${Date.now()}`,name:"Novo plano PMOC",status:"Em configuração",createdAt:new Date().toLocaleString("pt-BR"),periodicity:"Mensal",equipmentIds:[]})}><Plus size={15}/> Novo plano</button></div>
    <div className="tabs pmoc-tabs">{(["PMOC","Retrofit","Refrigerantes","Habilitação"] as const).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {tab==="PMOC" && <><div className="kpi-grid pmoc-kpis"><article><span className="pmoc-kpi-icon"><FileText size={18}/></span><div><small>PLANOS ATIVOS</small><strong>{plans.length}</strong><p>planos cadastrados</p></div></article><article><span className="pmoc-kpi-icon"><CalendarClock size={18}/></span><div><small>COM CRONOGRAMA</small><strong>{scheduled}</strong><p>próximas execuções definidas</p></div></article><article><span className="pmoc-kpi-icon"><UserRoundCheck size={18}/></span><div><small>RESP. TÉCNICO</small><strong>{documented}</strong><p>{pending?`${pending} pendente(s)`:"documentação vinculada"}</p></div></article><article><span className="pmoc-kpi-icon"><AlertTriangle size={18}/></span><div><small>DOCUMENTOS</small><strong>{soon}</strong><p>{soon?"vencendo em até 30 dias":"sem alertas próximos"}</p></div></article></div><div className="pmoc-table-card"><div className="pmoc-table-head"><div><h3>Planos de manutenção</h3><p>Visão operacional dos contratos e próximos atendimentos.</p></div></div><div className="table-wrap"><table className="pmoc-table"><thead><tr><th>CLIENTE</th><th>UNIDADE / SETOR</th><th>PERIODICIDADE</th><th>PRÓXIMA MANUTENÇÃO</th><th>RESPONSÁVEL TÉCNICO</th><th>SITUAÇÃO</th></tr></thead><tbody>{plans.map(plan=><tr key={plan.id}><td><strong>{plan.client||plan.name||"Plano sem cliente"}</strong></td><td>{[plan.unit,plan.sector].filter(Boolean).join(" • ")||"—"}</td><td>{plan.periodicity}</td><td>{nextPmocDate(plan)||<span className="pmoc-muted">Definir cronograma</span>}</td><td>{plan.technicalResponsible||<span className="pmoc-warning">Pendente</span>}</td><td><span className={plan.technicalResponsible?"pmoc-pill ok":"pmoc-pill pending"}>{plan.technicalResponsible?<><CheckCircle2 size={12}/> Regular</>:<><AlertTriangle size={12}/> Atenção</>}</span></td></tr>)}</tbody></table></div>{!plans.length&&<div className="pmoc-empty"><CalendarClock size={30}/><h4>Nenhum plano PMOC cadastrado</h4><p>Crie o primeiro plano para organizar periodicidade, equipamentos e responsável técnico.</p></div>}</div><button className="primary-btn" onClick={()=>onSave("PMOC",{id:`PMOC-${Date.now()}`,name:"Novo plano PMOC",status:"Em configuração",createdAt:new Date().toLocaleString("pt-BR"),periodicity:"Mensal",equipmentIds:[]})}><Plus size={15}/> Novo plano PMOC</button></>}
    {tab==="Retrofit" && <div className="catalog-edit-form"><label>Investimento total<input type="number" min="0" value={retrofit.investment} onChange={e=>setRetrofit({...retrofit,investment:Number(e.target.value)||0})}/></label><label>Potência atual (kW)<input type="number" min="0" step="0.01" value={retrofit.currentKw} onChange={e=>setRetrofit({...retrofit,currentKw:Number(e.target.value)||0})}/></label><label>Potência proposta (kW)<input type="number" min="0" step="0.01" value={retrofit.proposedKw} onChange={e=>setRetrofit({...retrofit,proposedKw:Number(e.target.value)||0})}/></label><label>Horas/mês<input type="number" min="0" value={retrofit.hoursPerMonth} onChange={e=>setRetrofit({...retrofit,hoursPerMonth:Number(e.target.value)||0})}/></label><label>Tarifa (R$/kWh)<input type="number" min="0" step="0.01" value={retrofit.tariff} onChange={e=>setRetrofit({...retrofit,tariff:Number(e.target.value)||0})}/></label><div className="wide pmoc-status-note"><span><b>ESTIMATIVA:</b> consumo atual {money(estimate.current)}/mês • proposto {money(estimate.proposed)}/mês • economia {money(estimate.monthly)}/mês • payback {estimate.paybackMonths?`${estimate.paybackMonths.toFixed(1)} meses`:"não calculável"}. Depende de uso, tarifa, ambiente e manutenção.</span></div><button className="primary-btn" onClick={()=>onSave("Retrofits",{id:`RET-${Date.now()}`,name:"Estudo de retrofit",status:"Estimativa",createdAt:new Date().toLocaleString("pt-BR"),...retrofit,...estimate})}><FileText size={15}/> Salvar estimativa</button></div>}
    {tab==="Refrigerantes" && <div className="table-wrap"><table><thead><tr><th>FLUIDO</th><th>LOTE</th><th>DISPONÍVEL</th><th>ÚLTIMA MOVIMENTAÇÃO</th></tr></thead><tbody>{fluids.map(fluid=><tr key={fluid.id}><td><ThermometerSnowflake size={15}/> {fluid.name}</td><td>{fluid.lot||"—"}</td><td>{refrigerantAvailable(fluid).toFixed(2)} {fluid.unit}</td><td>{fluid.movements?.[0]?.type||"Sem movimentações"}</td></tr>)}</tbody></table></div>}
    {tab==="Habilitação" && <><p className="agenda-hint"><CheckCircle2 size={14}/> {soon?`${soon} documento(s) vencendo ou vencido(s).`:"Documentação sem alertas próximos."}</p><div className="table-wrap"><table><thead><tr><th>CATEGORIA</th><th>DOCUMENTO</th><th>VALIDADE</th><th>RESPONSÁVEL</th></tr></thead><tbody>{documents.map(doc=><tr key={doc.id}><td>{doc.category}</td><td>{doc.name}</td><td>{doc.expiresAt||"Sem validade"}</td><td>{doc.responsible||"—"}</td></tr>)}</tbody></table></div></>}
  </section>
}
