"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, FileText, Plus, ShieldCheck, ThermometerSnowflake } from "lucide-react";
import { nextPmocDate, refrigerantAvailable, retrofitEstimate, type PmocPlan, type Refrigerant, type TechnicalDocument } from "@/lib/technical-compliance";

type Props={ plans:PmocPlan[]; fluids:Refrigerant[]; documents:TechnicalDocument[]; onSave:(module:string,record:any)=>Promise<boolean>|void };
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function TechnicalCompliancePanel({plans,fluids,documents,onSave}:Props){
  const [tab,setTab]=useState<"PMOC"|"Retrofit"|"Refrigerantes"|"Habilitação">("PMOC");
  const [retrofit,setRetrofit]=useState({investment:0,currentKw:0,proposedKw:0,hoursPerMonth:220,tariff:1});
  const estimate=useMemo(()=>retrofitEstimate(retrofit),[retrofit]);
  const soon=documents.filter(item=>item.expiresAt&&new Date(item.expiresAt)<=new Date(Date.now()+30*864e5)).length;
  return <section className="customer-panel technical-compliance-panel">
    <div className="panel-head"><div><span className="section-kicker"><ShieldCheck size={12}/> TÉCNICO E DOCUMENTAL</span><h2>PMOC, retrofit e conformidade</h2><p>Registros novos, separados do estoque físico e sem alterar históricos existentes.</p></div></div>
    <div className="tabs">{(["PMOC","Retrofit","Refrigerantes","Habilitação"] as const).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {tab==="PMOC" && <><div className="kpi-grid"><article><small>PLANOS</small><strong>{plans.length}</strong></article><article><small>PRÓXIMAS EXECUÇÕES</small><strong>{plans.filter(p=>nextPmocDate(p)).length}</strong></article><article><small>DOCUMENTAÇÃO</small><strong>{plans.filter(p=>p.technicalResponsible).length}</strong></article></div><div className="table-wrap"><table><thead><tr><th>CLIENTE</th><th>UNIDADE / SETOR</th><th>PERIODICIDADE</th><th>PRÓXIMA MANUTENÇÃO</th><th>RESPONSÁVEL TÉCNICO</th></tr></thead><tbody>{plans.map(plan=><tr key={plan.id}><td>{plan.client}</td><td>{[plan.unit,plan.sector].filter(Boolean).join(" • ")||"—"}</td><td>{plan.periodicity}</td><td>{nextPmocDate(plan)||"Definir cronograma"}</td><td>{plan.technicalResponsible||"Pendente"}</td></tr>)}</tbody></table></div><button className="primary-btn" onClick={()=>onSave("PMOC",{id:`PMOC-${Date.now()}`,name:"Novo plano PMOC",status:"Em configuração",createdAt:new Date().toLocaleString("pt-BR"),periodicity:"Mensal",equipmentIds:[]})}><Plus size={15}/> Novo plano PMOC</button></>}
    {tab==="Retrofit" && <div className="catalog-edit-form"><label>Investimento total<input type="number" min="0" value={retrofit.investment} onChange={e=>setRetrofit({...retrofit,investment:Number(e.target.value)||0})}/></label><label>Potência atual (kW)<input type="number" min="0" step="0.01" value={retrofit.currentKw} onChange={e=>setRetrofit({...retrofit,currentKw:Number(e.target.value)||0})}/></label><label>Potência proposta (kW)<input type="number" min="0" step="0.01" value={retrofit.proposedKw} onChange={e=>setRetrofit({...retrofit,proposedKw:Number(e.target.value)||0})}/></label><label>Horas/mês<input type="number" min="0" value={retrofit.hoursPerMonth} onChange={e=>setRetrofit({...retrofit,hoursPerMonth:Number(e.target.value)||0})}/></label><label>Tarifa (R$/kWh)<input type="number" min="0" step="0.01" value={retrofit.tariff} onChange={e=>setRetrofit({...retrofit,tariff:Number(e.target.value)||0})}/></label><div className="wide pmoc-status-note"><span><b>ESTIMATIVA:</b> consumo atual {money(estimate.current)}/mês • proposto {money(estimate.proposed)}/mês • economia {money(estimate.monthly)}/mês • payback {estimate.paybackMonths?`${estimate.paybackMonths.toFixed(1)} meses`:"não calculável"}. Depende de uso, tarifa, ambiente e manutenção.</span></div><button className="primary-btn" onClick={()=>onSave("Retrofits",{id:`RET-${Date.now()}`,name:"Estudo de retrofit",status:"Estimativa",createdAt:new Date().toLocaleString("pt-BR"),...retrofit,...estimate})}><FileText size={15}/> Salvar estimativa</button></div>}
    {tab==="Refrigerantes" && <div className="table-wrap"><table><thead><tr><th>FLUIDO</th><th>LOTE</th><th>DISPONÍVEL</th><th>ÚLTIMA MOVIMENTAÇÃO</th></tr></thead><tbody>{fluids.map(fluid=><tr key={fluid.id}><td><ThermometerSnowflake size={15}/> {fluid.name}</td><td>{fluid.lot||"—"}</td><td>{refrigerantAvailable(fluid).toFixed(2)} {fluid.unit}</td><td>{fluid.movements?.[0]?.type||"Sem movimentações"}</td></tr>)}</tbody></table></div>}
    {tab==="Habilitação" && <><p className="agenda-hint"><CheckCircle2 size={14}/> {soon?`${soon} documento(s) vencendo ou vencido(s).`:"Documentação sem alertas próximos."}</p><div className="table-wrap"><table><thead><tr><th>CATEGORIA</th><th>DOCUMENTO</th><th>VALIDADE</th><th>RESPONSÁVEL</th></tr></thead><tbody>{documents.map(doc=><tr key={doc.id}><td>{doc.category}</td><td>{doc.name}</td><td>{doc.expiresAt||"Sem validade"}</td><td>{doc.responsible||"—"}</td></tr>)}</tbody></table></div></>}
  </section>
}
