"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, HardHat, Package, Plus, RefreshCw, Ruler, UserRound } from "lucide-react";

type Unit = { id: string; block: string; lot: number; name?: string; kind?: string; status?: string };
type Contact = { id: string; name: string; contact_type: "engenharia" | "fiscalizacao"; role_name?: string; email?: string; phone?: string; is_active?: boolean };
type Change = { id: string; block_code?: string; unit_code?: string; environment_name?: string; work_stage?: string; original_measure?: string; new_measure?: string; measure_unit?: string; description: string; reason?: string; requested_by?: string; requested_at?: string; status: string };
type Consumption = { id: string; block_code?: string; unit_code?: string; work_stage: string; product_id: string; planned_quantity?: number; final_quantity: number; waste_percent?: number; status: string };

const labels: Record<string, string> = { solicitada: "Solicitada", em_analise: "Em análise", aprovada: "Aprovada", em_execucao: "Em execução", executada: "Executada", conferida: "Conferida", concluida: "Concluída", rejeitada: "Rejeitada", cancelada: "Cancelada", previsto: "Previsto", confirmado: "Confirmado", estornado: "Estornado" };
const statuses = ["solicitada", "em_analise", "aprovada", "em_execucao", "executada", "conferida", "concluida", "rejeitada", "cancelada"];

export function WorkOperationsPanel({ workId, units, responsibleUser }: { workId: string; units: Unit[]; responsibleUser: string }) {
  const [tab, setTab] = useState<"engenharia" | "alteracoes" | "materiais">("engenharia");
  const [contacts, setContacts] = useState<Contact[]>([]); const [changes, setChanges] = useState<Change[]>([]); const [consumptions, setConsumptions] = useState<Consumption[]>([]);
  const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  const [contact, setContact] = useState({ name: "", type: "engenharia", role: "", email: "", phone: "" });
  const [change, setChange] = useState({ unit: "", environment: "", stage: "", original: "", next: "", unitOfMeasure: "m", description: "", reason: "" });
  const [consumption, setConsumption] = useState({ unit: "", stage: "", product: "", planned: "", final: "", waste: "0", status: "confirmado" });
  const unitOptions = useMemo(() => units.map(unit => ({ value: unit.id, label: unit.kind === "common" ? `Área comum • ${unit.name || unit.id}` : `Quadra ${unit.block} • Casa ${String(unit.lot).padStart(2, "0")}` })), [units]);
  const load = async () => { setLoading(true); try { const [contactsResult, changesResult, consumptionResult] = await Promise.all([fetch(`/api/work-contacts?workId=${encodeURIComponent(workId)}`), fetch(`/api/work-changes?workId=${encodeURIComponent(workId)}`), fetch(`/api/work-consumptions?workId=${encodeURIComponent(workId)}`)]); const [a, b, c] = await Promise.all([contactsResult.json(), changesResult.json(), consumptionResult.json()]); if (contactsResult.ok) setContacts(a.contacts || []); if (changesResult.ok) setChanges(b.changes || []); if (consumptionResult.ok) setConsumptions(c.consumptions || []); } catch { setNotice("Não foi possível carregar os dados complementares da obra."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [workId]);
  const post = async (url: string, body: unknown) => { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Não foi possível salvar."); return result; };
  const addContact = async () => { if (!contact.name.trim()) return setNotice("Informe o nome do responsável."); try { await post("/api/work-contacts", { workId, name: contact.name, contactType: contact.type, roleName: contact.role, email: contact.email, phone: contact.phone, isActive: true, isPrimary: contacts.length === 0 }); setContact({ name: "", type: "engenharia", role: "", email: "", phone: "" }); setNotice("✓ Contato da obra salvo."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar o contato."); } };
  const addChange = async () => { if (!change.description.trim()) return setNotice("Descreva a alteração solicitada."); const selected = units.find(unit => unit.id === change.unit); try { await post("/api/work-changes", { workId, blockCode: selected?.block || null, unitCode: selected?.id || null, environmentName: change.environment, workStage: change.stage, originalMeasure: change.original, newMeasure: change.next, measureUnit: change.unitOfMeasure, description: change.description, reason: change.reason, requestedBy: responsibleUser, status: "solicitada" }); setChange({ unit: "", environment: "", stage: "", original: "", next: "", unitOfMeasure: "m", description: "", reason: "" }); setNotice("✓ Alteração de medida registrada. O status da unidade não foi modificado."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível registrar a alteração."); } };
  const updateChange = async (id: string, status: string) => { try { const response = await fetch("/api/work-changes", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setNotice("✓ Situação da alteração atualizada."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível atualizar a alteração."); } };
  const addConsumption = async () => { if (!consumption.stage.trim() || !consumption.product.trim() || !consumption.final.trim()) return setNotice("Informe etapa, produto e quantidade final."); const selected = units.find(unit => unit.id === consumption.unit); try { await post("/api/work-consumptions", { workId, blockCode: selected?.block || null, unitCode: selected?.id || null, workStage: consumption.stage, productId: consumption.product, plannedQuantity: consumption.planned || 0, finalQuantity: consumption.final, wastePercent: consumption.waste || 0, status: consumption.status }); setConsumption({ unit: "", stage: "", product: "", planned: "", final: "", waste: "0", status: "confirmado" }); setNotice("✓ Consumo da obra registrado."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível registrar o consumo."); } };
  const openChanges = changes.filter(item => !["concluida", "rejeitada", "cancelada"].includes(item.status));
  return <section className="work-operations-panel"><header><div><span>OPERAÇÃO DA OBRA</span><h3>Engenharia, alterações e materiais</h3><p>Registros complementares e auditáveis — sem alterar automaticamente a etapa da casa.</p></div><div className="work-operations-kpis"><b>{openChanges.length}<small>alterações abertas</small></b><b>{consumptions.filter(item => item.status === "confirmado").length}<small>consumos confirmados</small></b><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw size={14}/> Atualizar</button></div></header>
    <nav><button className={tab === "engenharia" ? "active" : ""} onClick={() => setTab("engenharia")}><HardHat size={15}/> Engenharia</button><button className={tab === "alteracoes" ? "active" : ""} onClick={() => setTab("alteracoes")}><Ruler size={15}/> Alterações de medidas {openChanges.length ? <b>{openChanges.length}</b> : null}</button><button className={tab === "materiais" ? "active" : ""} onClick={() => setTab("materiais")}><Package size={15}/> Materiais e consumo</button></nav>
    {notice && <p className="work-operations-notice">{notice}</p>}
    {tab === "engenharia" && <div className="work-operations-body"><div className="work-operation-form"><h4><UserRound size={16}/> Cadastro de engenharia/fiscalização</h4><div className="work-operation-fields"><label>Nome<input value={contact.name} onChange={event => setContact({ ...contact, name: event.target.value })}/></label><label>Tipo<select value={contact.type} onChange={event => setContact({ ...contact, type: event.target.value })}><option value="engenharia">Engenharia</option><option value="fiscalizacao">Fiscalização</option></select></label><label>Função<input value={contact.role} onChange={event => setContact({ ...contact, role: event.target.value })}/></label><label>E-mail<input type="email" value={contact.email} onChange={event => setContact({ ...contact, email: event.target.value })}/></label><label>Telefone<input value={contact.phone} onChange={event => setContact({ ...contact, phone: event.target.value })}/></label></div><button className="primary-btn" type="button" onClick={() => void addContact()}><Plus size={15}/> Salvar responsável</button></div><div className="work-operation-list">{contacts.length ? contacts.map(item => <article key={item.id}><HardHat size={18}/><div><b>{item.name}</b><small>{item.contact_type === "engenharia" ? "Engenharia" : "Fiscalização"} • {item.role_name || "Função não informada"}</small><small>{item.email || item.phone || "Sem contato informado"}</small></div><em>{item.is_active === false ? "Inativo" : "Ativo"}</em></article>) : <p>Nenhum responsável de engenharia cadastrado.</p>}</div></div>}
    {tab === "alteracoes" && <div className="work-operations-body"><div className="work-operation-form"><h4><Ruler size={16}/> Nova alteração de medida/projeto</h4><div className="work-operation-fields"><label>Casa/lote ou área<select value={change.unit} onChange={event => setChange({ ...change, unit: event.target.value })}><option value="">Selecione</option>{unitOptions.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Ambiente<input value={change.environment} onChange={event => setChange({ ...change, environment: event.target.value })} placeholder="Ex.: Sala"/></label><label>Etapa<input value={change.stage} onChange={event => setChange({ ...change, stage: event.target.value })} placeholder="Ex.: Rede frigorígena"/></label><label>Medida original<input value={change.original} onChange={event => setChange({ ...change, original: event.target.value })}/></label><label>Nova medida<input value={change.next} onChange={event => setChange({ ...change, next: event.target.value })}/></label><label>Unidade<select value={change.unitOfMeasure} onChange={event => setChange({ ...change, unitOfMeasure: event.target.value })}><option>m</option><option>cm</option><option>mm</option><option>un</option></select></label><label className="wide">Descrição<textarea value={change.description} onChange={event => setChange({ ...change, description: event.target.value })} placeholder="Descreva a alteração solicitada pela engenharia..."/></label><label className="wide">Motivo<textarea value={change.reason} onChange={event => setChange({ ...change, reason: event.target.value })} placeholder="Justificativa ou observação técnica..."/></label></div><button className="primary-btn" type="button" onClick={() => void addChange()}><Plus size={15}/> Salvar alteração</button></div><div className="work-operation-list">{changes.length ? changes.map(item => <article key={item.id}><Ruler size={18}/><div><b>{item.unit_code || "Obra"} • {item.environment_name || "Ambiente não informado"}</b><small>{item.work_stage || "Etapa não informada"} • {item.original_measure || "—"} → {item.new_measure || "—"} {item.measure_unit || ""}</small><small>{item.description}</small></div><label>Situação<select value={item.status} onChange={event => void updateChange(item.id, event.target.value)}>{statuses.map(status => <option key={status} value={status}>{labels[status]}</option>)}</select></label></article>) : <p>Nenhuma alteração de medida cadastrada.</p>}</div></div>}
    {tab === "materiais" && <div className="work-operations-body"><div className="work-operation-form"><h4><Package size={16}/> Consumo de material por unidade</h4><div className="work-operation-fields"><label>Casa/lote ou área<select value={consumption.unit} onChange={event => setConsumption({ ...consumption, unit: event.target.value })}><option value="">Obra inteira / sem unidade</option>{unitOptions.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Etapa<input value={consumption.stage} onChange={event => setConsumption({ ...consumption, stage: event.target.value })} placeholder="Ex.: AG. FRIGORÍGENA"/></label><label>Produto/código<input value={consumption.product} onChange={event => setConsumption({ ...consumption, product: event.target.value })} placeholder="Código do produto"/></label><label>Previsto<input inputMode="decimal" value={consumption.planned} onChange={event => setConsumption({ ...consumption, planned: event.target.value })}/></label><label>Quantidade final<input inputMode="decimal" value={consumption.final} onChange={event => setConsumption({ ...consumption, final: event.target.value })}/></label><label>Perda (%)<input inputMode="decimal" value={consumption.waste} onChange={event => setConsumption({ ...consumption, waste: event.target.value })}/></label></div><button className="primary-btn" type="button" onClick={() => void addConsumption()}><Plus size={15}/> Registrar consumo</button></div><div className="work-operation-list">{consumptions.length ? consumptions.map(item => <article key={item.id}><Package size={18}/><div><b>{item.product_id}</b><small>{item.unit_code || "Obra"} • {item.work_stage}</small><small>Previsto: {item.planned_quantity ?? 0} • Final: {item.final_quantity} • Perda: {item.waste_percent ?? 0}%</small></div><em>{labels[item.status] || item.status}</em></article>) : <p>Nenhum consumo registrado nesta obra.</p>}</div></div>}
  </section>;
}
