export type GoNoGoInput={score:number;missingDocuments:number;expiredDocuments:number;criticalRisks:number;marginPercent?:number;daysToDeadline?:number;distanceKm?:number};
export function evaluateGoNoGo(i:GoNoGoInput){let points=i.score;const reasons:string[]=[];if(i.missingDocuments){points-=Math.min(30,i.missingDocuments*8);reasons.push(`${i.missingDocuments} documento(s) ausente(s)`)}if(i.expiredDocuments){points-=Math.min(25,i.expiredDocuments*10);reasons.push(`${i.expiredDocuments} documento(s) vencido(s)`)}if(i.criticalRisks){points-=Math.min(35,i.criticalRisks*15);reasons.push(`${i.criticalRisks} risco(s) crítico(s)`)}if(i.marginPercent!==undefined&&i.marginPercent<8){points-=20;reasons.push("margem abaixo de 8%")}if(i.daysToDeadline!==undefined&&i.daysToDeadline<2){points-=15;reasons.push("prazo inferior a 2 dias")}const final=Math.max(0,Math.min(100,points));return{score:final,decision:final>=70?"Participar":final>=45?"Participar com atenção":"Não recomendado",reasons:reasons.length?reasons:["sem bloqueadores relevantes identificados"]}}
export type CostComposition={equipment:number;materials:number;labor:number;taxes:number;freight:number;travel:number;lodging:number;meals:number;warranty:number;financial:number;contingency:number;marginPercent:number};
export function composeTenderPrice(c:CostComposition){const direct=["equipment","materials","labor","taxes","freight","travel","lodging","meals","warranty","financial","contingency"].reduce((s,k)=>s+Math.max(0,Number(c[k as keyof CostComposition])||0),0);const margin=Math.max(0,Math.min(90,Number(c.marginPercent)||0));const floor=margin>=100?direct:direct/(1-margin/100);return{cost:Math.round(direct*100)/100,floorPrice:Math.round(floor*100)/100,marginPercent:margin}}
export type RiskSignal={title:string;severity:"Crítico"|"Atenção";reason:string};
export function tenderRisks(text:string):RiskSignal[]{const rules:[[RegExp,string,string],...Array<[RegExp,string,string]>]=[[/multa|penalidade/i,"Sanções contratuais","Revisar percentuais, gatilhos e limites de multa."],[/garantia contratual|garantia de execu/i,"Garantia contratual","Confirmar percentual, modalidade e prazo."],[/24\s*h|emergencial|imediat/i,"Atendimento emergencial","Validar capacidade de SLA e plantão."],[/crea|respons[aá]vel t[eé]cnico|art\b/i,"Responsabilidade técnica","Confirmar CREA/ART e profissional habilitado."],[/estoque m[ií]nimo|pronta entrega/i,"Estoque obrigatório","Validar capital de giro e disponibilidade."],[/visita t[eé]cnica/i,"Visita técnica","Registrar prazo e comprovante exigido."]];return rules.filter(([r])=>r.test(text)).map(([,title,reason])=>({title,severity:/multa|garantia contratual/i.test(title)?"Crítico":"Atenção",reason}))}
export type PublicContractBalance={contracted:number;committed:number;executed:number;invoiced:number;received:number};
export function publicContractBalance(b:PublicContractBalance){return{availableToCommit:Math.max(0,b.contracted-b.committed),remainingToExecute:Math.max(0,b.committed-b.executed),remainingToInvoice:Math.max(0,b.executed-b.invoiced),remainingToReceive:Math.max(0,b.invoiced-b.received)}}
export function procurementKpis(records:Array<{status?:string;estimatedValue?:number;proposalValue?:number;awardedValue?:number;remainingBalance?:number}>){return records.reduce((a,r)=>{const s=(r.status||"").toLowerCase();if(/nova|analisar|interessante/.test(s))a.open+=Number(r.estimatedValue||0);if(/particip|disputa|habilita/.test(s))a.participating+=Number(r.proposalValue||r.estimatedValue||0);if(/homolog|ganh|contrat/.test(s))a.won+=Number(r.remainingBalance??r.awardedValue??0);return a},{open:0,participating:0,won:0})}
