-- ProAR Release Governance
-- Estrutura aditiva para promover releases com segurança:
-- Interno -> Homologação -> Canary -> Produção.
-- Não remove nem sobrescreve dados operacionais existentes.

create table if not exists public.proar_release_environments (
  code text primary key check (code in ('internal','homologation','canary','production')),
  name text not null,
  alias text,
  description text,
  customer_facing boolean not null default false,
  requires_approval boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.proar_release_environments (code,name,alias,description,customer_facing,requires_approval)
values
  ('internal','ProAR Interno','teste.proar.online','Primeiro ambiente. Somente equipe ProAR e dados sintéticos.',false,false),
  ('homologation','Homologação','homologacao.proar.online','Release candidate validada pela equipe antes de clientes.',false,false),
  ('canary','Canary',null,'Liberação controlada para tenants selecionados.',true,true),
  ('production','Produção',null,'Versão aprovada para PolarTech e demais clientes.',true,true)
on conflict (code) do nothing;

create table if not exists public.proar_releases (
  id text primary key,
  version text not null unique,
  commit_sha text not null,
  deployment_id text not null,
  schema_version text not null,
  minimum_schema_version text not null,
  channel text not null default 'internal' check (channel in ('internal','homologation','canary','production')),
  status text not null default 'draft' check (status in ('draft','testing','approved','scheduled','rolling_out','active','failed','rolled_back')),
  title text not null,
  summary text,
  affected_modules jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  migrations jsonb not null default '[]'::jsonb,
  compatibility jsonb not null default '{}'::jsonb,
  quality_gate jsonb not null default '{}'::jsonb,
  approval_required boolean not null default true,
  created_by text not null,
  approved_by text,
  approved_at timestamptz,
  scheduled_at timestamptz,
  promoted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists proar_releases_channel_status_idx
  on public.proar_releases(channel,status,created_at desc);

create table if not exists public.proar_release_targets (
  id bigint generated by default as identity primary key,
  release_id text not null references public.proar_releases(id),
  company_id text,
  environment_code text not null references public.proar_release_environments(code),
  alias text not null,
  previous_version text,
  previous_deployment_id text,
  target_version text not null,
  target_deployment_id text not null,
  status text not null default 'pending' check (status in ('pending','validating','scheduled','deploying','active','failed','blocked','rolled_back')),
  health_status text check (health_status is null or health_status in ('ok','warning','error')),
  snapshot_id bigint,
  error_code text,
  error_message text,
  scheduled_at timestamptz,
  applied_at timestamptz,
  rolled_back_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (release_id, environment_code, alias)
);

create index if not exists proar_release_targets_company_idx
  on public.proar_release_targets(company_id,created_at desc);

create index if not exists proar_release_targets_status_idx
  on public.proar_release_targets(status,scheduled_at);

create table if not exists public.proar_tenant_release_settings (
  company_id text primary key,
  release_channel text not null default 'production' check (release_channel in ('internal','homologation','canary','production')),
  update_policy text not null default 'automatic' check (update_policy in ('automatic','manual','pinned','scheduled')),
  pinned_version text,
  current_version text,
  current_deployment_id text,
  schema_version text not null default '2026.10.06',
  maintenance_mode boolean not null default false,
  maintenance_message text,
  scheduled_update_at timestamptz,
  last_health_at timestamptz,
  last_health_status text check (last_health_status is null or last_health_status in ('ok','warning','error')),
  last_error_code text,
  last_error_message text,
  updated_at timestamptz not null default now()
);

create index if not exists proar_tenant_release_settings_channel_idx
  on public.proar_tenant_release_settings(release_channel,update_policy);

create table if not exists public.proar_feature_flags (
  flag_key text primary key,
  name text not null,
  description text,
  module_name text,
  status text not null default 'active' check (status in ('active','paused','retired')),
  default_enabled boolean not null default false,
  internal_enabled boolean not null default true,
  homologation_enabled boolean not null default false,
  canary_percent integer not null default 0 check (canary_percent between 0 and 100),
  production_enabled boolean not null default false,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.proar_feature_flag_overrides (
  flag_key text not null references public.proar_feature_flags(flag_key),
  company_id text not null,
  enabled boolean not null,
  reason text,
  updated_by text,
  updated_at timestamptz not null default now(),
  primary key (flag_key,company_id)
);

create table if not exists public.proar_release_checks (
  id bigint generated by default as identity primary key,
  release_id text not null references public.proar_releases(id),
  company_id text,
  environment_code text not null,
  stage text not null check (stage in ('pre','post','continuous')),
  check_key text not null,
  status text not null check (status in ('ok','warning','error')),
  code text,
  detail text,
  latency_ms integer,
  checked_at timestamptz not null default now()
);

create index if not exists proar_release_checks_release_idx
  on public.proar_release_checks(release_id,checked_at desc);

alter table public.proar_release_environments enable row level security;
alter table public.proar_releases enable row level security;
alter table public.proar_release_targets enable row level security;
alter table public.proar_tenant_release_settings enable row level security;
alter table public.proar_feature_flags enable row level security;
alter table public.proar_feature_flag_overrides enable row level security;
alter table public.proar_release_checks enable row level security;

comment on table public.proar_releases is
  'Catálogo de releases controladas do ProAR com aprovação, compatibilidade e histórico de promoção.';
comment on table public.proar_release_targets is
  'Estado por alias/tenant para versionamento fixado, rollout, health check e rollback.';
comment on table public.proar_tenant_release_settings is
  'Política de atualização, versão atual, schema e modo manutenção por tenant.';
comment on table public.proar_feature_flags is
  'Feature flags graduais por ambiente, percentual canary e produção.';
