create table if not exists public.proar_system_incidents (
  id text primary key,
  company_id text,
  module text not null,
  operation text not null,
  code text not null,
  severity text not null check (severity in ('info','warning','error','critical')),
  user_message text,
  technical_message text,
  request_id text,
  route text,
  metadata jsonb not null default '{}'::jsonb,
  resolved_at timestamptz,
  resolved_by text,
  created_at timestamptz not null default now()
);

create index if not exists proar_system_incidents_company_created_idx
  on public.proar_system_incidents (company_id, created_at desc);

create index if not exists proar_system_incidents_open_idx
  on public.proar_system_incidents (created_at desc)
  where resolved_at is null;

alter table public.proar_system_incidents enable row level security;

create table if not exists public.proar_health_snapshots (
  id bigint generated by default as identity primary key,
  company_id text,
  service text not null,
  state text not null check (state in ('ok','warning','error')),
  latency_ms integer,
  code text,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists proar_health_snapshots_company_checked_idx
  on public.proar_health_snapshots (company_id, checked_at desc);

alter table public.proar_health_snapshots enable row level security;
